#!/bin/bash
#
#
# chkconfig: 345 99 99
#
# description: pipeline2d init
# processname: pipeline2d

# Source function library.
. /etc/rc.d/init.d/functions

DIR=/opt/daisy-pipeline2/bin/
LOG=/var/log/daisy-pipeline2/pipeline2.log
PROG=./pipeline2
OPTIONS=""

umask 0002

daemon_pid() {
    echo `ps aux | grep daisy-pipeline2/ | grep -v grep | awk '{print $2}'`
}

start() {
      PID=$(daemon_pid)
      if [[ $PID ]] ; then
        echo "$PROG is already running"
        RETVAL=1
      else
        echo -n "Starting $PROG"
        cd $DIR
        if [[ "$USER" == "pipeline2" ]] ; then
			daemon $PROG $OPTIONS >$LOG 2>&1 &
		else
			daemon --user pipeline2 $PROG $OPTIONS >$LOG 2>&1 &
		fi
        RETVAL=$?
      fi
      echo
      return $RETVAL
}

stop() {
      PID=$(pidof -x /etc/init.d/pipeline2d)
      if [[ $PID ]] ; then
        echo -n "Stopping $PROG"
        kill -15 $(daemon_pid)
        sleep 1
        if [[ $(daemon_pid) ]] ; then
          kill -9 $(daemon_pid)
        fi
        RETVAL=$?
      else
        echo "$PROG not running"
        RETVAL=1
      fi
      echo
      return $RETVAL
}

status() {
     pid=$(daemon_pid)
     if [ -n "$pid" ] ; then
      	echo "Pipeline2 daemon is running with pid: $pid"
     else
       	echo "Pipeline2 daemon is not running"
      	exit 3
     fi
}

# See how we were called.
RETVAL=0

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  status)
        status
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart|status}"
        exit 1
esac

exit $?